# Generated by Django 6.0.3 on 2026-03-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapeuticApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Brain', 'Brain'), ('Lightbulb', 'Lightbulb'), ('Target', 'Target'), ('Sparkles', 'Sparkles'), ('BookOpen', 'Book Open'), ('Heart', 'Heart')], default='Brain', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
