# Generated by Django 6.0.3 on 2026-03-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0002_therapeuticapproach'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('FileText', 'File Text'), ('BookOpen', 'Book Open'), ('Calendar', 'Calendar'), ('Lightbulb', 'Lightbulb')], default='FileText', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_action', models.CharField(help_text='URL, "contact", or "tel:number"', max_length=200)),
                ('color', models.CharField(choices=[('teal', 'Teal'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='teal', max_length=20)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('action', models.CharField(help_text='e.g., "tel:0799240254"', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SupportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Video', 'Video'), ('Users', 'Users'), ('Calendar', 'Calendar')], default='Users', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('color', models.CharField(choices=[('teal', 'Teal'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], default='teal', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WellnessTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Heart', 'Heart'), ('Users', 'Users'), ('Lightbulb', 'Lightbulb'), ('BookOpen', 'Book Open'), ('Phone', 'Phone')], default='Heart', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
