# Generated by Django 6.0.3 on 2026-03-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_educationalresource_emergencycontact_supportoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_badge', models.CharField(default='Our Mission', max_length=100)),
                ('mission_title', models.CharField(default='Why We Exist', max_length=200)),
                ('mission_description', models.TextField()),
                ('vision_badge', models.CharField(default='Our Vision', max_length=100)),
                ('vision_title', models.CharField(default="The Future We're Building", max_length=200)),
                ('vision_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mission & Vision',
                'verbose_name_plural': 'Mission & Vision',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Heart', 'Heart'), ('Users', 'Users'), ('Shield', 'Shield'), ('TrendingUp', 'Trending Up'), ('BookOpen', 'Book Open')], default='Heart', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhoWeServe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Who We Serve', max_length=200)),
                ('description', models.TextField()),
                ('items', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Who We Serve',
                'verbose_name_plural': 'Who We Serve',
            },
        ),
    ]
