# Generated by Django 6.0.3 on 2026-03-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0004_missionvision_stat_whoweserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled BlogPost', max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('author_image_url', models.URLField(blank=True)),
                ('featured_image_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('read_time', models.IntegerField(default=5, help_text='Reading time in minutes')),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('primary_button_text', models.CharField(max_length=100)),
                ('primary_button_link', models.CharField(max_length=200)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100)),
                ('secondary_button_link', models.CharField(blank=True, max_length=200)),
                ('background_color', models.CharField(default='teal-600', max_length=20)),
                ('text_color', models.CharField(default='white', max_length=20)),
                ('background_image_url', models.URLField(blank=True)),
                ('section_type', models.CharField(choices=[('standard', 'Standard'), ('split', 'Split Screen'), ('full_width', 'Full Width')], default='standard', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Event', max_length=500)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('support_group', 'Support Group'), ('seminar', 'Seminar'), ('webinar', 'Webinar')], max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=500)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True, help_text='For online events')),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('registered_count', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('featured_image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Slide', max_length=200)),
                ('title_highlight', models.CharField(blank=True, help_text='Text to highlight in title', max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('badge_text', models.CharField(blank=True, max_length=200)),
                ('primary_button_text', models.CharField(default='Book Now', max_length=100)),
                ('primary_button_link', models.CharField(default='contact', max_length=200)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100)),
                ('secondary_button_link', models.CharField(blank=True, max_length=200)),
                ('background_image_url', models.URLField(blank=True, help_text='URL to background image')),
                ('background_video_url', models.URLField(blank=True, help_text='URL to background video')),
                ('overlay_opacity', models.FloatField(default=0.5, help_text='Overlay opacity (0-1)')),
                ('overlay_color', models.CharField(default='#000000', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('animation_type', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom')], default='fade', max_length=50)),
                ('slide_duration', models.IntegerField(default=5000, help_text='Duration in milliseconds')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('specialties', models.JSONField(default=list, help_text='List of specialties')),
                ('education', models.JSONField(default=list, help_text='List of education credentials')),
                ('languages', models.JSONField(default=list, help_text='List of languages spoken')),
                ('years_experience', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero Section (Legacy)', 'verbose_name_plural': 'Hero Section (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_contact_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='phone', max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='icon_color',
            field=models.CharField(choices=[('teal', 'Teal'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink')], default='teal', max_length=20),
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., "60 minutes"', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to service image'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to service video'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='orange-500', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(default='© 2024 Suzstar Counseling. All rights reserved.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='teal-600', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='blue-600', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='animation_duration',
            field=models.IntegerField(default=2000, help_text='Duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='stat',
            name='prefix',
            field=models.CharField(blank=True, help_text='e.g., "$"', max_length=20),
        ),
        migrations.AddField(
            model_name='stat',
            name='suffix',
            field=models.CharField(blank=True, help_text='e.g., "+", "%", "k"', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AddField(
            model_name='therapeuticapproach',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='therapeuticapproach',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapeuticapproach',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='value',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='value',
            name='title',
            field=models.CharField(default='Untitled Value', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(choices=[('MessageCircle', 'Message Circle'), ('Users', 'Users'), ('BookOpen', 'Book Open'), ('Heart', 'Heart'), ('Shield', 'Shield'), ('Clock', 'Clock'), ('CheckCircle', 'Check Circle'), ('Phone', 'Phone'), ('Sparkles', 'Sparkles'), ('Star', 'Star'), ('Award', 'Award')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(default='Untitled Feature', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='Untitled HeroSection', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('MessageCircle', 'Message Circle'), ('Users', 'Users'), ('BookOpen', 'Book Open'), ('Heart', 'Heart'), ('Shield', 'Shield'), ('Clock', 'Clock'), ('CheckCircle', 'Check Circle'), ('Phone', 'Phone'), ('Sparkles', 'Sparkles'), ('Star', 'Star'), ('Award', 'Award')], default='Heart', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='Untitled Service', max_length=200),
        ),
        migrations.AlterField(
            model_name='stat',
            name='icon',
            field=models.CharField(choices=[('Heart', 'Heart'), ('Users', 'Users'), ('Shield', 'Shield'), ('TrendingUp', 'Trending Up'), ('BookOpen', 'Book Open'), ('Calendar', 'Calendar'), ('Clock', 'Clock'), ('Award', 'Award')], default='Heart', max_length=50),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='therapeuticapproach',
            name='icon',
            field=models.CharField(choices=[('Brain', 'Brain'), ('Lightbulb', 'Lightbulb'), ('Target', 'Target'), ('Sparkles', 'Sparkles'), ('BookOpen', 'Book Open'), ('Heart', 'Heart'), ('Users', 'Users'), ('Shield', 'Shield')], default='Brain', max_length=50),
        ),
        migrations.AlterField(
            model_name='value',
            name='icon',
            field=models.CharField(choices=[('Heart', 'Heart'), ('Shield', 'Shield'), ('Users', 'Users'), ('BookOpen', 'Book Open'), ('TrendingUp', 'Trending Up'), ('Star', 'Star'), ('Award', 'Award'), ('Sparkles', 'Sparkles')], default='Heart', max_length=50),
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('resources', 'Resources'), ('contact', 'Contact')], max_length=100)),
                ('section_name', models.CharField(max_length=200)),
                ('title', models.CharField(default='Untitled Section', max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('background_type', models.CharField(choices=[('color', 'Color'), ('image', 'Image'), ('video', 'Video'), ('gradient', 'Gradient')], default='color', max_length=50)),
                ('background_value', models.CharField(blank=True, max_length=500)),
                ('text_color', models.CharField(default='gray-900', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['page', 'order'],
                'unique_together': {('page', 'section_name')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counseling.teammember'),
        ),
    ]
